# Container image variables
container:
  name: nginx # Container name
  image: nginx:latest # Container image that you deploy to the cluster

containerSidecar:
  name: hasher # Container name
  image: hasher:latest # Container image that you deploy to the cluster

# Name and identifier variables
metadata:
  deploymentName: nginx-hasher-integrity # Set the unique name for deployment schema
  appName: nginx-app # Application name label

# Name of Container Monitor App service account
serviceAccount: hasher # Service account name

# Number of replicas
replicaCount: 1

# Configuration file variables
configMap:
  processName: nginx # Container process name
  mountPath: etc/nginx # Tracked folder path
