{{- $sa := print .Release.Name "-" .Values.serviceAccount -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.metadata.deploymentName }}
  labels:
    app: {{ .Values.metadata.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.appName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.appName }}
      annotations:
        integrity-monitor.scnsoft.com/inject: "true"
        {{ .Values.configMap.processName }}.integrity-monitor.scnsoft.com/monitoring-paths: {{ join "," .Values.configMap.mountPaths }}
    spec:
      serviceAccountName: {{ $sa }}
      shareProcessNamespace: true
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}
          imagePullPolicy: IfNotPresent
          stdin: true
          tty: true

        - name: {{ .Values.containerSidecar.name }}
          image: {{ .Values.containerSidecar.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.releaseNameDB }}-postgresql
                  key: password
            {{- if .Values.minio.enabled }}
            - name: MINIO_SERVER_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.secret.name }}
                  key: {{ .Values.minio.secret.userKey }}
            - name: MINIO_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.secret.name }}
                  key: {{ .Values.minio.secret.passwordKey }}
            {{- end }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DEPLOYMENT_TYPE
              value: deployment
          args:
            - --monitoring-options={{ .Values.configMap.processName }}={{ join "," .Values.configMap.mountPaths }}
            - --verbose={{ .Values.configMap.verbose }}
            - --db-host={{ .Values.releaseNameDB }}-postgresql
            - --db-port={{ .Values.db.port }}
            - --db-name={{ .Values.db.database }}
            - --db-user={{ .Values.db.username }}
            - --splunk-url={{ .Values.configMap.splunkUrl }}
            - --splunk-token={{ .Values.configMap.splunkToken }}
            - --splunk-insecure-skip-verify={{ .Values.configMap.splunkInsecureSkipVerify }}
            {{- if .Values.configMap.syslog.enabled }}
            - --syslog-enabled={{ .Values.configMap.syslog.enabled }}
            - --syslog-host={{ .Values.configMap.syslog.host }}
            - --syslog-port={{ .Values.configMap.syslog.port }}
            - --syslog-proto={{ .Values.configMap.syslog.proto }}
            {{- end }}
            {{- if .Values.minio.enabled }}
            - --minio-enabled={{ .Values.minio.enabled }}
            - --minio-host={{ .Values.minio.server.host }}:{{ .Values.minio.server.port }}
            {{- end }}
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "[ -f /tmp/integrity-monitor ] && pidof {{ .Values.configMap.liveness.appName }}"
            initialDelaySeconds: 10
            periodSeconds: 5
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          stdin: true
          tty: true
